NETWORK_PASSPHRASE="Public Global Stellar Network ; October 2014"

[DOCUMENTATION]
ORG_NAME="Happymealtech - New Era"
ORG_URL="https://happymealtech.github.io/ame/"
ORG_DESCRIPTION="Collezione di asset digitali in argento e platino su Stellar."
ORG_LOGO="https://happymealtech.github.io/ame/AMEN.jpeg"

[[CURRENCIES]]
code="AMEN"
issuer="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
display_decimals=2
name="AMEN"
desc="Asset digitale sacro della collezione Platinum 2026."
image="https://happymealtech.github.io/ame/AMEN.jpeg"
conditions="Questo token non ha valore monetario o finanziario intrinseco."

[[ACCOUNTS]]
name="Issuer Account"
public_key="GD22GBKOUYWC3C2QDZPMT27GBD2L6STAPXN2QEZB3HX4GNISW3P7XSQK"
